name: Pipeline for build

on:
  push:
    tags:
      - '*.*.*'

jobs:
  
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Auth Docker
        run: |
          echo ${{ secrets.ACCESS_TOKEN }} | docker login ghcr.io -u rahadiangg --password-stdin

      - name: Build image for ${{ matrix.app }}
        working-directory: ${{ matrix.app }}
        run: |
          docker build -t ghcr.io/rahadiangg/pleno-${{ matrix.app }}:${GITHUB_REF#refs/tags/} --target=final .

      - name: Push image for ${{ matrix.app }}
        run: |
          docker push ghcr.io/rahadiangg/pleno-${{ matrix.app }}:${GITHUB_REF#refs/tags/}