name: Pipeline for build

on:
  push:
    tags:
      - '*.*.*'

jobs:
  
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Auth to GCP
        id: auth
        uses: google-github-actions/auth@v1
        with :
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      
      - name: Auth Docker
        run: |
          gcloud --quiet auth configure-docker asia-southeast2-docker.pkg.dev

      - name: Build & push image
        run: |
          docker buildx create --user
          docker buildx build -t asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${GITHUB_REPOSITORY#*/}:${GITHUB_REF#refs/tags/} --push .
  
  # deploy-cloud-run:
  #   runs-on: ubuntu-22.04

  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
      

