name: Pull request pipeline
on:
  pull_request:

jobs:

  lint_and_test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      
      - name: Unit Testing
        run: go test -v ./...

        # just mocking integration test
      - name: Integration test
        run: echo "Integration testing finished..."

        # just mocking end to end test
      - name: End to end test
        run: echo "End to end testing finished..."

      - name: Static code analysis
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}